# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BindRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_top', models.PositiveIntegerField()),
                ('range_price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.Bind')),
            ],
            options={
                'ordering': ['range_top'],
            },
        ),
        migrations.CreateModel(
            name='XeroCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('cost_per_page', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
                ('bind_cost', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('is_one_sided', models.BooleanField(default=False)),
                ('is_two_sided', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='XeroList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='XeroBaseBookCalc',
            fields=[
                ('xerocalc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.XeroCalc')),
                ('xero_pages_real', models.IntegerField(default=0)),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booklist.Book')),
            ],
            bases=('calculator.xerocalc',),
        ),
        migrations.CreateModel(
            name='XeroBookCalc',
            fields=[
                ('xerocalc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.XeroCalc')),
                ('book_pages_arabic', models.PositiveIntegerField(default=0)),
                ('book_pages_roman', models.PositiveIntegerField(default=0)),
            ],
            bases=('calculator.xerocalc',),
        ),
        migrations.CreateModel(
            name='XeroSimpleCalc',
            fields=[
                ('xerocalc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.XeroCalc')),
                ('number_of_cards_from_form', models.PositiveIntegerField(default=0)),
                ('is_mix_with_two_sided_advantage', models.BooleanField(default=False)),
                ('is_mix_with_one_sided_advantage', models.BooleanField(default=False)),
                ('two_sided_pages_in_mix', models.PositiveIntegerField(default=0)),
                ('one_sided_pages_in_mix', models.PositiveIntegerField(default=0)),
            ],
            bases=('calculator.xerocalc',),
        ),
        migrations.AddField(
            model_name='xerocalc',
            name='bind_ranges',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='calculator.Bind'),
        ),
        migrations.AddField(
            model_name='xerocalc',
            name='xero_cost_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calculator.XeroList'),
        ),
    ]
