# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xerosimplecalc',
            name='is_cards_in_form',
            field=models.BooleanField(default=False),
        ),
    ]
