# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_xerosimplecalc_is_cards_in_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='XeroByWeightCalc',
            fields=[
                ('xerocalc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='calculator.XeroCalc')),
                ('weight', models.PositiveIntegerField(default=0)),
                ('is_bind', models.BooleanField(default=False)),
                ('is_mix_with_two_sided_advantage', models.BooleanField(default=False)),
                ('is_mix_with_one_sided_advantage', models.BooleanField(default=False)),
                ('two_sided_pages_in_mix', models.PositiveIntegerField(default=0)),
                ('one_sided_pages_in_mix', models.PositiveIntegerField(default=0)),
            ],
            bases=('calculator.xerocalc',),
        ),
    ]
